sudo: false
dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.31.0
os:
  - linux
addons:
  apt:
    packages:
    - libudev-dev

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
