# SPDX-FileCopyrightText: 2018-2022 Joonas Javanainen <joonas.javanainen@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

name: ci
on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Update Ubuntu package lists
        run: sudo apt update
        if: runner.os == 'Linux'
      - name: Install Ubuntu packages
        run: sudo apt install libudev-dev
        if: runner.os == 'Linux'
      - name: Cache dependencies
        uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
      - name: Run checks
        run: cargo check --all
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

  compile_and_test:
    name: Compile and run tests
    needs: [check]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.56.0
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Update Ubuntu package lists
        run: sudo apt update
        if: runner.os == 'Linux'
      - name: Install Ubuntu packages
        run: sudo apt install libudev-dev
        if: runner.os == 'Linux'
      - name: Cache dependencies
        uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
      - name: Compile
        run: cargo test --all --no-run
      - name: Test
        run: cargo test --all
